openapi: 3.0.0
info:
  title: makroappservice-backend
  description: makroappservice-backend api
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local server
tags:
  - name: file-sheets
    description: Read and write xlsx
paths:
  #file-sheets
  /file-sheets/process:
    post:
      tags:
        - file-sheets
      summary: Process xlsx file
      parameters:
        - in: query
          name: doc_type
          schema:
            type: string
            enum: [special_brief, weekly_brief]
          required: false
          description: is special brief
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/response_import'
        '404':
          description: Not found document
          content:
            application/json:
              schema:
                $ref: '#/components/responses/404_not_found'
        400:
          description: Not found scope
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error'

components:
  schemas:
    #RESPONSES
    api_response:
      title: ApiResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          type: object
          description: Object according to the requested resource
        status:
          type: integer
          description: HTTP code status
    api_response_sring:
      title: ApiResponseString
      required:
        - result
        - status
      type: object
      properties:
        result:
          type: string
          description: Object according to the requested resource
        status:
          type: integer
          description: HTTP code status
    api_error:
      title: ApiError
      required:
        - message
        - code
      type: object
      properties:
        message:
          type: string
          description: Message that describes the error
        code:
          type: integer
          description: Code of error
        metadata:
          type: object
          description: More info of error
    list_reponse:
      title: ListResponse
      required:
        - items
        - total
      type: object
      properties:
        items:
          type: array
          items:
            type: object
          description: response elements according to the resource
        total:
          type: integer
          description: total of items saved
    api_list_reponse:
      title: ApiListResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          $ref: '#/components/schemas/list_reponse'
        status:
          type: integer
          description: HTTP code status
    list_paginated_response:
      title: ListPaginatedResponse
      required:
        - items
        - total
      type: object
      properties:
        items:
          type: array
          items:
            type: object
          description: response elements according to the resource
        total:
          type: integer
          description: total of items saved
        next:
          type: string
          description: next page
        prev:
          type: string
          description: prev page
    api_list_paginated_response:
      title: ApiListPaginatedResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          $ref: '#/components/schemas/list_paginated_response'
        status:
          type: integer
          description: HTTP code status
    api_import_response:
      title: ApiImportResponse
      type: object
      properties:
        summary:
          type: object
          properties:
            total:
              type: integer
              description: total of items saved
            success:
              type: integer
              description: total of items saved
            failed:
              type: integer
              description: total of items that failed
            execution_time:
              type: string
              description: total time of execution
            warning:
              type: integer
              description: total of items that have warnings with GM
        template_errors:
          type: array
          items:
            type: string
        rows_errors:
          type: array
          items:
            type: object
            properties:
              row:
                type: integer
                description: row number
              errors:
                type: array
                items:
                  type: string
  responses:
    response_import:
      $ref: '#/components/schemas/api_import_response'
    response:
      $ref: '#/components/schemas/api_response'
    response_string:
      $ref: '#/components/schemas/api_response_sring'
    list_response:
      $ref: '#/components/schemas/api_list_reponse'
    error:
      $ref: '#/components/schemas/api_error'
    404_not_found:
      $ref: '#/components/schemas/api_error'
    list_paginated_response:
      $ref: '#/components/schemas/api_list_paginated_response'
